<?php


namespace RouterUnit\Domain;

use PHPUnit\Framework\TestCase;
use Router\Application\MatchRouteUseCase;
use Router\Domain\Router;

class RouterTest extends TestCase
{
    private $matchRouteUseCase;

    private $router;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->router = new Router();
    }

    /** @test */
    public function routeNotExistingThrowsException()
    {
        $this->expectException(\Exception::class);

        $this->router->get('/noexiste', function() { return "texto";});
    }

    /** @test */
    public function existingRouteReturnsKnownString()
    {

        $this->assertEquals($this->router->get('/post', function() { return "texto";}), "texto");

    }
}