<?php


namespace RouterUnit\Domain;

use PHPUnit\Framework\TestCase;

class RouterTest extends TestCase
{
    private $router;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->router = new \Router\Domain\Router();
    }

    /** @test */
    public function trueAssertsToTrue()
    {
        $this->assertTrue(true);
    }
}