<?php


namespace RouterUnit\Domain;

use PHPUnit\Framework\TestCase;
use Router\Application\MatchRouteUseCase;
use Router\Domain\Router;

class RouterTest extends TestCase
{
    private $matchRouteUseCase;

    private $router;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->matchRouteUseCase = $this->createMock(MatchRouteUseCase::class);
        $this->router = new Router($this->matchRouteUseCase);
    }

    /** @test */
    public function routeNotExistingThrowsException()
    {
        $this->expectException(\Exception::class);

        $this->matchRouteUseCase
            ->method('execute')
            ->willReturn(['match' => false, "args" => []]);

        $this->router->get('/noexiste', function() { return "texto";});
    }
}